name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: 1n0isg2n2pvHaPF4TCJMCgX56uF_7r32j82yuJE9JDwNK1uR8
        USER_PASS: 7895123
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 100h
